openapi: 3.0.0
info:
  title: anstalld_service API
  version: 1.0.0
  description: API för att hantera anställda
servers:
  - url: /anstalld

paths:
  /:
    get:
      summary: Hämta alla anställda
      responses:
        '200':
          description: Lista av anställda
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/anstalld'
    post:
      summary: Lägg till en ny anställd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anstalld'
      responses:
        '200':
          description: ID på ny anställd
          content:
            application/json:
              schema:
                type: integer
  /{id}:
    get:
      summary: Hämta en anställd via ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: En anställd
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/anstalld'
    delete:
      summary: Ta bort en anställd
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Antal rader borttagna
          content:
            application/json:
              schema:
                type: integer
components:
  schemas:
    anstalld:
      type: object
      properties:
        anstalld_id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
        hire_date:
          type: string
          format: date
        manager_id:
          type: integer
        job_title:
          type: string
